sudo: false
language: ruby
rvm:
- 2.2.2
cache: bundler
addons:
  codeclimate:
    repo_token: 3fde4939e0c228c28af16f423dea66f393ba55ee8c06e6878e1b44035de7daa7
  postgresql: '9.4'
before_script:
- psql -c "create database travis_ci_test;" -U postgres
- cp config/database.travis.yml config/database.yml
deploy:
  provider: opsworks
  access_key_id: AKIAIX2XPBWY2OUEGGXA
  secret_access_key:
    secure: TKGjNiIwvkhwsFpN7aL9c2jE+HZiomkY2sF2M3xO2CnRgQSfOotaj3gGAQaG4B69zxfm5PfJ+uxbdB9oYxs1cQnSapxYquS7RGcO/Ib/22CUcvFlMyUywjUioQXcgoHzj2up9YGxj+vmS3b/T9ZGh+L5UUB0wwrn3MvTYrJWMw0=
  app-id: 1cd0a7e6-627b-4f24-80a5-fdde59ad904c
  on:
    repo: rapidturtle/com-twincresttech-www
    branch: master
    rvm: 2.2.2
notifications:
  slack:
    secure: Hhbli7awQ9XCYiXAUR4BEmtj4v2RWeN7tnqfWknVTciurMoUAqVHvz+AHtnv6tkrBqOxPTJTebaClWQrXuOa53fGHM4a6P3QPtv5qfI8i4kKBeQ2lORCCVMeBWEo0NiYGBM6EkJHrS+qxwcuopIu4b3npViAAGx/xLHmjWj/OVU=
