name: Deploy to GitHub Pages

on:
  pull_request:
    branches:
      - master
    types:
      - closed   

jobs:
  build-deploy:
    if: github.events.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Install
        run: yarn install
        
      - name: Build
        run: yarn run build:prod
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.2.0
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./dist/twincrest
